---
- name: Group MariaDB hosts based on shards
  add_host:
    name: "{{ item }}"
    groups: "{{ hostvars[item]['mariadb_shard_group'] }}"
  loop: "{{ groups['mariadb'] }}"
  changed_when: false

- include_tasks: "{{ kolla_action }}.yml"
