---
features:
  - |
    Prometheus version 2.x deployment added. This version is enabled by
    default and replaces a forward-incompatible version 1.x. A variable
    ``prometheus_use_v1`` can be set to ``yes`` to preserve version
    1.x deployment with its data. Otherwise, Prometheus will start with
    a new volume, ignoring all previously collected metrics.
upgrade:
  - |
    New Prometheus version ignores previously stored metrics. If you
    want to keep using 1.x with the old data, set ``prometheus_use_v1``
    variable to ``yes``. The old data is not removed, please read the
    docs for details. Please also make sure you adapt changes in command
    line options if they were ever customized in your environment because
    Prometheus 2.x has different syntax (``--option`` with double dashes
    instead of ``-option``).
