---
upgrade:
  - |
    Combine ``trove-taskmanager.conf`` and ``trove-conductor.conf``
    to ``trove.conf``. you should move all customized opts in
    ``/etc/kolla/config/trove/trove-taskmanager.conf`` or
    ``/etc/kolla/config/trove/trove-conductor.conf`` to
    ``/etc/kolla/config/trove/trove.conf``.
    ``trove-taskmanager.conf`` and ``trove-conductor.conf`` are no
    longer used in wallaby
