---
features:
  - |
    Implements [Configure tap-as-a-service plugin on neutron containers].
    Adds the needed changes and configurations in order to use the
    neutron plugin, tap-as-a-service, to create por mirrors using
    `openstack tap` commands.
    `Blueprint configure-taas-plugin
    <https://blueprints.launchpad.net/kolla-ansible/+spec/configure-taas-plugin>`__
