---
fixes:
  - |
    Fix cyborg api doesn't listen on api interface. change host to
    host_ip in cyborg.conf. See the `cyborg documentation
    <https://docs.openstack.org/cyborg/latest/configuration/sample-config.html>`__
