---
features:
  - |
    Changes target names in Prometheus to user-friendly, Ansible inventory
    based values.
upgrade:
  - |
    Changes Prometheus targets naming. This makes their names more user
    friendly but also creates a completely new set of a time series data.
    New target names are taken from Ansible inventory and have the exporter
    port number stripped off. Any Grafana dashboard that relies on a specific,
    hard-coded naming pattern for the targets will stop showing metrics after
    the upgrade.
