---
upgrade:
  - |
    Customizing Neutron Linux bridge and Open vSwitch Agents config via
    ``ml2_conf.ini`` is removed. The config has been split out for these
    agents into ``linuxbridge_agent.ini`` and ``openvswitch_agent.ini``
    respectively.  The old behaviour was deprecated in Ussuri.
