---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ redis_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    container_engine: "{{ kolla_container_engine }}"
    name:
      - redis
  check_mode: false
  register: container_facts

- name: Checking free port for Redis
  vars:
    redis: "{{ redis_services['redis'] }}"
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ redis_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['redis'] is not defined
    - inventory_hostname in groups[redis.group]
    - redis.enabled | bool
