---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ rally_services }}"

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  run_once: True
  register: rally_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/rally/"
      skip: true

- name: Set rally policy file
  set_fact:
    rally_policy_file: "{{ rally_policy.results.0.stat.path | basename }}"
    rally_policy_file_path: "{{ rally_policy.results.0.stat.path }}"
  when:
    - rally_policy.results

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ rally_services }}"
  notify:
    - Restart rally container

- name: Copying over rally.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/rally.conf.j2"
      - "{{ node_custom_config }}/rally.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ item.key }}.conf"
    mode: "0660"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ rally_services }}"
  notify:
    - Restart rally container

- name: Copying over existing policy file
  template:
    src: "{{ rally_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ rally_policy_file }}"
    mode: "0660"
  become: true
  when:
    - rally_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ rally_services }}"
  notify:
    - Restart rally container
