---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ trove_services }}"

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  run_once: True
  delegate_to: localhost
  register: trove_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/trove/"
      skip: true

- name: Set trove policy file
  set_fact:
    trove_policy_file: "{{ trove_policy.results.0.stat.path | basename }}"
    trove_policy_file_path: "{{ trove_policy.results.0.stat.path }}"
  when:
    - trove_policy.results

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ trove_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over trove conf files
  vars:
    services_need_confs:
      - trove-conductor
      - trove-taskmanager
  merge_configs:
    sources:
      - "{{ role_path }}/templates/{{ item.key }}.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/{{ item.key }}.conf"
      - "{{ node_custom_config }}/trove/{{ item.key }}.conf"
      - "{{ node_custom_config }}/trove/{{ inventory_hostname }}/{{ item.key }}.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ item.key }}.conf"
    mode: "0660"
  become: true
  when:
    - item.key in services_need_confs
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ trove_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over trove-guestagent.conf
  vars:
    services_need_confs:
      - trove-taskmanager
  merge_configs:
    sources:
      - "{{ role_path }}/templates/trove-guestagent.conf.j2"
      - "{{ node_custom_config }}/trove-guestagent.conf"
      - "{{ node_custom_config }}/trove/trove-guestagent.conf"
      - "{{ node_custom_config }}/trove/{{ inventory_hostname }}/trove-guestagent.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/trove-guestagent.conf"
    mode: "0660"
  become: true
  when:
    - item.key in services_need_confs
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ trove_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over trove.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/trove.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/trove.conf"
      - "{{ node_custom_config }}/trove/{{ item.key }}.conf"
      - "{{ node_custom_config }}/trove/{{ inventory_hostname }}/trove.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/trove.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ trove_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over existing policy file
  template:
    src: "{{ trove_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ trove_policy_file }}"
    mode: "0660"
  when:
    - trove_policy_file is defined
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ trove_services }}"
  notify:
    - Restart {{ item.key }} container

- import_tasks: check-containers.yml
  when: kolla_action != "config"
