---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_trove_auth }}"
    service_ks_register_services: "{{ trove_ks_services }}"
    service_ks_register_users: "{{ trove_ks_users }}"
