---
project_name: "congress"

congress_services:
  congress-api:
    container_name: congress_api
    group: congress-api
    enabled: true
    image: "{{ congress_api_image_full }}"
    volumes: "{{ congress_api_default_volumes + congress_api_extra_volumes }}"
    dimensions: "{{ congress_api_dimensions }}"
    haproxy:
      congress_api:
        enabled: "{{ enable_congress }}"
        mode: "http"
        external: false
        port: "{{ congress_api_port }}"
      congress_api_external:
        enabled: "{{ enable_congress }}"
        mode: "http"
        external: true
        port: "{{ congress_api_port }}"
  congress-policy-engine:
    container_name: congress_policy_engine
    group: congress-policy-engine
    enabled: true
    image: "{{ congress_policy_engine_image_full }}"
    volumes: "{{ congress_policy_engine_default_volumes + congress_policy_engine_extra_volumes }}"
    dimensions: "{{ congress_policy_engine_dimensions }}"
  congress-datasource:
    container_name: congress_datasource
    group: congress-datasource
    enabled: true
    image: "{{ congress_datasource_image_full }}"
    volumes: "{{ congress_datasource_default_volumes + congress_datasource_extra_volumes }}"
    dimensions: "{{ congress_datasource_dimensions }}"


####################
# Database
####################
congress_database_name: "congress"
congress_database_user: "{% if use_preconfigured_databases | bool and use_common_mariadb_user | bool %}{{ database_user }}{% else %}congress{% endif %}"
congress_database_address: "{{ database_address | put_address_in_context('url') }}:{{ database_port }}"


####################
# Docker
####################
congress_install_type: "{{ kolla_install_type }}"
congress_tag: "{{ openstack_tag }}"

congress_policy_engine_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ congress_install_type }}-congress-policy-engine"
congress_policy_engine_tag: "{{ congress_tag }}"
congress_policy_engine_image_full: "{{ congress_policy_engine_image }}:{{ congress_policy_engine_tag }}"

congress_datasource_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ congress_install_type }}-congress-datasource"
congress_datasource_tag: "{{ congress_tag }}"
congress_datasource_image_full: "{{ congress_datasource_image }}:{{ congress_datasource_tag }}"

congress_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ congress_install_type }}-congress-api"
congress_api_tag: "{{ congress_tag }}"
congress_api_image_full: "{{ congress_api_image }}:{{ congress_api_tag }}"

congress_api_dimensions: "{{ default_container_dimensions }}"
congress_policy_engine_dimensions: "{{ default_container_dimensions }}"
congress_datasource_dimensions: "{{ default_container_dimensions }}"

congress_api_default_volumes:
  - "{{ node_config_directory }}/congress-api/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "kolla_logs:/var/log/kolla/"
  - "{{ kolla_dev_repos_directory ~ '/congress/congress:/var/lib/kolla/venv/lib/python' ~ distro_python_version ~ '/site-packages/congress' if congress_dev_mode | bool else '' }}"
congress_policy_engine_default_volumes:
  - "{{ node_config_directory }}/congress-policy-engine/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "kolla_logs:/var/log/kolla/"
  - "{{ kolla_dev_repos_directory ~ '/congress/congress:/var/lib/kolla/venv/lib/python' ~ distro_python_version ~ '/site-packages/congress' if congress_dev_mode | bool else '' }}"
congress_datasource_default_volumes:
  - "{{ node_config_directory }}/congress-datasource/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "kolla_logs:/var/log/kolla/"
  - "{{ kolla_dev_repos_directory ~ '/congress/congress:/var/lib/kolla/venv/lib/python' ~ distro_python_version ~ '/site-packages/congress' if congress_dev_mode | bool else '' }}"

congress_extra_volumes: "{{ default_extra_volumes }}"
congress_api_extra_volumes: "{{ congress_extra_volumes }}"
congress_policy_engine_extra_volumes: "{{ congress_extra_volumes }}"
congress_datasource_extra_volumes: "{{ congress_extra_volumes }}"

####################
# OpenStack
####################
congress_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ congress_api_port }}"
congress_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ congress_api_port }}"
congress_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn | put_address_in_context('url') }}:{{ congress_api_port }}"

congress_logging_debug: "{{ openstack_logging_debug }}"

congress_keystone_user: "congress"

openstack_congress_auth: "{{ openstack_auth }}"


####################
# Kolla
####################
congress_git_repository: "{{ kolla_dev_repos_git }}/{{ project_name }}"
congress_dev_repos_pull: "{{ kolla_dev_repos_pull }}"
congress_dev_mode: "{{ kolla_dev_mode }}"
congress_source_version: "{{ kolla_source_version }}"

####################
# Keystone
####################
congress_ks_services:
  - name: "congress"
    type: "policy"
    description: "Congress Service"
    endpoints:
      - {'interface': 'admin', 'url': '{{ congress_admin_endpoint }}'}
      - {'interface': 'internal', 'url': '{{ congress_internal_endpoint }}'}
      - {'interface': 'public', 'url': '{{ congress_public_endpoint }}'}

congress_ks_users:
  - project: "service"
    user: "{{ congress_keystone_user }}"
    password: "{{ congress_keystone_password }}"
    role: "admin"
