---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ panko_services }}"

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  run_once: True
  register: panko_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/panko/"
      skip: true

- name: Set panko policy file
  set_fact:
    panko_policy_file: "{{ panko_policy.results.0.stat.path | basename }}"
    panko_policy_file_path: "{{ panko_policy.results.0.stat.path }}"
  when:
    - panko_policy.results

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ panko_services }}"
  notify:
    - Restart panko-api container

- name: Copying over panko.conf
  merge_configs:
    sources:
      - "{{ role_path }}/templates/panko.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/panko.conf"
      - "{{ node_custom_config }}/panko/{{ item.key }}.conf"
      - "{{ node_custom_config }}/panko/{{ inventory_hostname }}/{{ item.key }}.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/panko.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ panko_services }}"
  notify:
    - Restart panko-api container

- name: Copying over wsgi-panko files for services
  vars:
    service: "{{ panko_services['panko-api'] }}"
  template:
    src: "wsgi-panko.conf.j2"
    dest: "{{ node_config_directory }}/{{ item }}/wsgi-panko.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_items:
    - "panko-api"
  notify:
    - Restart panko-api container

- name: Copying over existing policy file
  template:
    src: "{{ panko_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ panko_policy_file }}"
    mode: "0660"
  become: true
  when:
    - panko_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ panko_services }}"
  notify:
    - Restart panko-api container
