---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_panko_auth }}"
    service_ks_register_services: "{{ panko_ks_services }}"
    service_ks_register_users: "{{ panko_ks_users }}"
