---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_glance_auth }}"
    service_ks_register_services: "{{ glance_ks_services }}"
    service_ks_register_users: "{{ glance_ks_users }}"
