---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}/providers.d"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ karbor_services }}"

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ karbor_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over karbor.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/karbor.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/karbor.conf"
      - "{{ node_custom_config }}/karbor/{{ item.key }}.conf"
      - "{{ node_custom_config }}/karbor/{{ inventory_hostname }}/karbor.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/karbor.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ karbor_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over provider configs
  vars:
    service_name: 'karbor-protection'
    service: "{{ karbor_services[service_name] }}"
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/{{ service_name }}/providers.d/"
    mode: "0660"
  become: true
  with_fileglob:
    - "{{ node_custom_config }}/karbor/{{ service_name }}/providers.d/*"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart karbor-protection container

- name: Copying over openstack-infra.conf
  vars:
    service_name: 'karbor-protection'
    service: "{{ karbor_services[service_name] }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/providers.d/openstack-infra.conf.j2"
      - "{{ node_custom_config }}/karbor/{{ service_name }}/providers.d/openstack-infra.conf"
    dest: "{{ node_config_directory }}/{{ service_name }}/providers.d/openstack-infra.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart karbor-protection container
