---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_karbor_auth }}"
    service_ks_register_services: "{{ karbor_ks_services }}"
    service_ks_register_users: "{{ karbor_ks_users }}"
