---
docker_version_min: '18.09'
docker_py_version_min: '3.4.1'
ansible_version_min: '2.14'
ansible_version_max: '2.15'

# Top level keys should match ansible_facts.distribution.
# These map to lists of supported releases (ansible_facts.distribution_release) or
# versions (ansible_facts.distribution_version or ansible_facts.distribution_major_version)
# for that distribution.
host_os_distributions:
  CentOS:
    - "9"
  Debian:
    - "bullseye"
    - "bookworm"
  openEuler:
    - "22.03"
  Rocky:
    - "9"
  Ubuntu:
    - "jammy"
