---
docker_version_min: '1.10.0'
docker_py_version_min: '2.0.0'
ansible_version_min: '2.9'
ansible_version_max: '2.9'

# Top level keys should match ansible_distribution.
# These map to lists of supported releases (ansible_distribution_release) or
# versions (ansible_distribution_version or ansible_distribution_major_version)
# for that distribution.
host_os_distributions:
  CentOS:
    - "8"
  Debian:
    - "buster"
  RHEL:
    - "8"
  Ubuntu:
    - "focal"
