---
- name: Check telegraf containers
  become: true
  kolla_container:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    pid_mode: "{{ item.value.pid_mode }}"
    dimensions: "{{ item.value.dimensions }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ telegraf_services }}"
  notify:
    - "Restart {{ item.key }} container"
