---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}/config"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ telegraf_services }}"

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over default config.json files
  template:
    src: "telegraf.json.j2"
    dest: "{{ node_config_directory }}/telegraf/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ telegraf_services }}"
  notify:
    - Restart telegraf container

- name: Copying over telegraf config file
  vars:
    service: "{{ telegraf_services['telegraf'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/telegraf/telegraf.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/telegraf/{{ inventory_hostname }}/telegraf.conf"
    - "{{ node_custom_config }}/telegraf/telegraf.conf"
    - "telegraf.conf.j2"
  notify:
    - Restart telegraf container

- name: Copying over telegraf plugin files
  vars:
    service: "{{ telegraf_services['telegraf'] }}"
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/telegraf/config"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - item.value.enabled | bool
  with_fileglob:
    - "{{ role_path }}/templates/config/*.conf"
  notify:
    - Restart telegraf container
