---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_neutron_auth }}"
    service_ks_register_services: "{{ neutron_ks_services }}"
    service_ks_register_users: "{{ neutron_ks_users }}"
