---
- import_tasks: neutron_plugin_agent_check.yml

- include_tasks: rolling_upgrade.yml
  when: neutron_enable_rolling_upgrade | bool

- include_tasks: legacy_upgrade.yml
  when: not neutron_enable_rolling_upgrade | bool
