---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ placement_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    container_engine: "{{ kolla_container_engine }}"
    name:
      - placement_api
  check_mode: false
  register: container_facts

- name: Checking free port for Placement API
  vars:
    placement_api: "{{ placement_services['placement-api'] }}"
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ placement_api_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['placement_api'] is not defined
    - inventory_hostname in groups[placement_api.group]
    - placement_api.enabled | bool
