---
- import_tasks: config.yml

- import_tasks: check-containers.yml

- include_tasks: clone.yml
  when:
    - horizon_dev_mode | bool

- include_tasks: bootstrap.yml
  when: horizon_backend_database | bool

- name: Flush handlers
  meta: flush_handlers
