---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ horizon_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    container_engine: "{{ kolla_container_engine }}"
    name:
      - horizon
  register: container_facts

- name: Checking free port for Horizon
  vars:
    horizon: "{{ horizon_services['horizon'] }}"
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ horizon_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['horizon'] is not defined
    - inventory_hostname in groups[horizon.group]
