---
- name: Checking host OS distribution
  fail:
    msg: >-
      Host OS distribution {{ ansible_facts.distribution }} is not supported.
      Supported distributions are: {{ host_os_distributions.keys() | join(', ') }}
  when: ansible_facts.distribution not in host_os_distributions

- name: Checking host OS release or version
  fail:
    msg: >-
      {{ ansible_facts.distribution }} release {{ ansible_facts.distribution_release }}
      version {{ ansible_facts.distribution_version }} is not supported.
      Supported releases are:
      {{ host_os_distributions[ansible_facts.distribution] | join(', ') }}
  when:
    - ansible_facts.distribution_release not in host_os_distributions[ansible_facts.distribution]
    - ansible_facts.distribution_version not in host_os_distributions[ansible_facts.distribution]
    - ansible_facts.distribution_major_version not in host_os_distributions[ansible_facts.distribution]
