---
- name: Fail if group loadbalancer not exists or it is empty
  fail:
    msg: >-
      Inventory's group loadbalancer does not exist or it is empty.
      Please update inventory, as haproxy group was renamed
      to loadbalancer in the Xena release.
  when:
    - enable_loadbalancer | bool
    - groups['loadbalancer'] is not defined or
      groups['loadbalancer'] | length < 1
