---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ vitrage_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    container_engine: "{{ kolla_container_engine }}"
    name:
      - vitrage_api
  check_mode: false
  register: container_facts

- name: Checking free port for vitrage API
  wait_for:
    host: "{{ 'api' | kolla_address }}"
    port: "{{ vitrage_api_port }}"
    connect_timeout: 1
    state: stopped
  when:
    - container_facts['vitrage_api'] is not defined
    - inventory_hostname in groups['vitrage-api']

- name: Checking custom prometheus_conf.yaml exists
  stat:
    path: "{{ node_custom_config }}/vitrage/prometheus_conf.yaml"
  delegate_to: localhost
  register: result
  run_once: true
  failed_when: not result.stat.exists
  when:
    - enable_vitrage_prometheus_datasource | bool
