---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_vitrage_auth }}"
    service_ks_register_services: "{{ vitrage_ks_services }}"
    service_ks_register_users: "{{ vitrage_ks_users }}"

- name: Adding vitrage user into admin project
  become: true
  kolla_toolbox:
    module_name: "os_user_role"
    module_args:
      user: "{{ vitrage_keystone_user }}"
      role: "admin"
      project: "admin"
      auth: "{{ openstack_vitrage_auth }}"
      endpoint_type: "{{ openstack_interface }}"
      cacert: "{{ openstack_cacert }}"
      region_name: "{{ openstack_region_name }}"
  run_once: True
