---
openstack_clients_pip_packages:
  - package: python-barbicanclient
    enabled: "{{ scenario == 'scenario_nfv' }}"
  - package: python-designateclient
    enabled: "{{ scenario == 'magnum' }}"
  - package: python-heatclient
    enabled: true
  - package: python-ironicclient
    enabled: "{{ scenario == 'ironic' }}"
  - package: python-ironic-inspector-client
    enabled: "{{ scenario == 'ironic' }}"
  - package: python-magnumclient
    enabled: "{{ scenario == 'magnum' }}"
  - package: python-masakariclient
    enabled: "{{ scenario == 'masakari' }}"
  - package: python-mistralclient
    enabled: "{{ scenario == 'scenario_nfv' }}"
  - package: python-octaviaclient
    enabled: "{{ scenario in ['octavia', 'ovn'] }}"
  - package: python-openstackclient
    enabled: true
  - package: python-tackerclient
    enabled: "{{ scenario == 'scenario_nfv' }}"
  - package: python-troveclient
    enabled: "{{ scenario == 'magnum' }}"
  - package: python-zunclient
    enabled: "{{ scenario == 'zun' }}"

openstack_clients_venv_base: "{{ ansible_user_dir }}"
openstack_clients_venv_name: "openstackclient-venv"
openstack_clients_venv_path: "{{ openstack_clients_venv_base }}/{{ openstack_clients_venv_name }}"
