---
- name: Check opensearch containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    dimensions: "{{ item.value.dimensions }}"
    environment: "{{ item.value.environment | default(omit) }}"
    healthcheck: "{{ item.value.healthcheck | default(omit) }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ opensearch_services }}"
  notify:
    - "Restart {{ item.key }} container"
