---
- import_tasks: register.yml

- include_tasks: bootstrap_xenapi.yml
  when:
    - inventory_hostname in groups['compute']
    - nova_compute_virt_type == "xenapi"

- include_tasks: clone.yml
  when: nova_dev_mode | bool

- import_tasks: config-host.yml

- import_tasks: config.yml

- include_tasks: config-nova-fake.yml
  when:
    - enable_nova_fake | bool
    - inventory_hostname in groups['compute']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['nova-api'] or
        inventory_hostname in groups['compute']

- import_tasks: create_cells.yml

- name: Flush handlers
  meta: flush_handlers

- import_tasks: discover_computes.yml
