---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_nova_auth }}"
    service_ks_register_services: "{{ nova_ks_services }}"
    service_ks_register_users: "{{ nova_ks_users }}"
