---
- name: Check common containers
  become: true
  kolla_container:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    dimensions: "{{ item.value.dimensions }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    environment: "{{ item.value.environment }}"
  when:
    - item.value | service_enabled_and_mapped_to_host
  with_dict: "{{ common_services }}"
  notify:
    - "Restart {{ item.key }} container"
