---
- import_tasks: register.yml

- import_tasks: config.yml

- import_tasks: check-containers.yml

- include_tasks: clone.yml
  when:
    - kuryr_dev_mode | bool

- name: Flush handlers
  meta: flush_handlers
