---
- include_tasks: remove-ha-all-policy.yml
  when: rabbitmq_remove_ha_all_policy | bool

- import_tasks: config.yml

- import_tasks: check-containers.yml

- import_tasks: bootstrap.yml

- name: Flush handlers
  meta: flush_handlers
