---
- name: Enable feature flags
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: "community.rabbitmq.rabbitmq_feature_flag"
    module_args:
      name: "{{ item }}"
    user: root
  become: true
  loop: "{{ rabbitmq_feature_flags }}"
