---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ murano_services }}"

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  run_once: True
  register: murano_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/murano/"
      skip: true

- name: Set murano policy file
  set_fact:
    murano_policy_file: "{{ murano_policy.results.0.stat.path | basename }}"
    murano_policy_file_path: "{{ murano_policy.results.0.stat.path }}"
  when:
    - murano_policy.results

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ murano_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over murano.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/murano.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/murano.conf"
      - "{{ node_custom_config }}/murano/{{ item.key }}.conf"
      - "{{ node_custom_config }}/murano/{{ inventory_hostname }}/murano.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/murano.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ murano_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over existing policy file
  template:
    src: "{{ murano_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ murano_policy_file }}"
    mode: "0660"
  when:
    - murano_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ murano_services }}"
  notify:
    - "Restart {{ item.key }} container"
