---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_murano_auth }}"
    service_ks_register_services: "{{ murano_ks_services }}"
    service_ks_register_users: "{{ murano_ks_users }}"
