---
- name: Cloning masakari source repository for development
  become: true
  git:
    repo: "{{ masakari_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ masakari_dev_repos_pull }}"
    version: "{{ masakari_source_version }}"

- name: Cloning masakari monitors source repository for development
  become: true
  git:
    repo: "{{ masakari_monitors_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/masakari-monitors"
    update: "{{ masakari_monitors_dev_repos_pull }}"
    version: "{{ masakari_monitors_source_version }}"
