---
- name: Cloning masakari source repository for development
  become: true
  git:
    repo: "{{ masakari_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ masakari_dev_repos_pull }}"
    version: "{{ masakari_source_version }}"

- name: Cloning masakarimonitors source repository for development
  become: true
  git:
    repo: "{{ masakarimonitors_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/masakari-monitors"
    update: "{{ masakarimonitors_dev_repos_pull }}"
    version: "{{ masakarimonitors_source_version }}"
