---
- import_tasks: config-host.yml

- import_tasks: config.yml

- name: Stopping all slave keepalived containers
  vars:
    key: "{{ 'ipv6' if api_address_family == 'ipv6' else 'ipv4_secondaries' }}"
    addresses: "{{ hostvars[inventory_hostname]['ansible_' + api_interface].get(key, []) | map(attribute='address') | list }}"
  become: true
  kolla_docker:
    action: "stop_container"
    common_options: "{{ docker_common_options }}"
    name: "keepalived"
  when: kolla_internal_vip_address not in addresses
  notify:
    - Restart keepalived container

- import_tasks: check-containers.yml

# NOTE(yoctozepto): haproxy role handlers should not be flushed early.
# site.yml handles all haproxy things in a dedicated play.
# This is to avoid extra haproxy service restart.
# See: https://bugs.launchpad.net/kolla-ansible/+bug/1875228
