---
- name: Stop and remove chrony container
  become: true
  kolla_docker:
    action: "stop_and_remove_container"
    name: chrony

- name: Remove config for chrony
  become: true
  file:
    path: "{{ node_config_directory }}/chrony"
    state: "absent"
