---
chrony_services:
  chrony:
    container_name: "chrony"
    group: "chrony"
    image: "{{ chrony_image_full }}"
    enabled: True
    privileged: True
    volumes: "{{ chrony_default_volumes + chrony_extra_volumes }}"
    dimensions: "{{ chrony_dimensions }}"

chrony_bindaddress: "{{ kolla_internal_vip_address }}"

####################
# Docker
####################
chrony_install_type: "{{ kolla_install_type }}"
chrony_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ chrony_install_type }}-chrony"
chrony_tag: "{{ openstack_tag }}"
chrony_image_full: "{{ chrony_image }}:{{ chrony_tag }}"

chrony_dimensions: "{{ default_container_dimensions }}"

chrony_default_volumes:
  - "{{ node_config_directory }}/chrony/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "kolla_logs:/var/log/kolla"
chrony_extra_volumes: "{{ default_extra_volumes }}"
