---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_searchlight_auth }}"
    service_ks_register_services: "{{ searchlight_ks_services }}"
    service_ks_register_users: "{{ searchlight_ks_users }}"
