---
- import_role:
    name: service-config-validate
  vars:
    service_config_validate_services: "{{ freezer_services }}"
    service_name: "{{ project_name }}"
    service_config_validation: "{{ freezer_config_validation }}"
