---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ freezer_services }}"

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  run_once: True
  register: freezer_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/freezer/"
      skip: true

- name: Set freezer policy file
  set_fact:
    freezer_policy_file: "{{ freezer_policy.results.0.stat.path | basename }}"
    freezer_policy_file_path: "{{ freezer_policy.results.0.stat.path }}"
  when:
    - freezer_policy.results

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ freezer_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over wsgi-freezer-api.conf
  vars:
    service: "{{ freezer_services['freezer-api'] }}"
  template:
    src: "wsgi-freezer-api.conf.j2"
    dest: "{{ node_config_directory }}/freezer-api/wsgi-freezer-api.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart freezer-api container

- name: Copying over freezer confs
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/freezer.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/freezer.conf"
      - "{{ node_custom_config }}/freezer/{{ item.key }}.conf"
      - "{{ node_custom_config }}/freezer/{{ inventory_hostname }}/{{ item.key }}.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/freezer.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ freezer_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over existing policy file
  template:
    src: "{{ freezer_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ freezer_policy_file }}"
    mode: "0660"
  become: true
  when:
    - freezer_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ freezer_services }}"
  notify:
    - "Restart {{ item.key }} container"
