---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ freezer_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    container_engine: "{{ kolla_container_engine }}"
    name:
      - freezer_api
  check_mode: false
  register: container_facts

- name: Checking free port for Freezer API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ freezer_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - inventory_hostname in groups[freezer_services['freezer-api']['group']]
    - container_facts['freezer_api'] is not defined
