---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_freezer_auth }}"
    service_ks_register_services: "{{ freezer_ks_services }}"
    service_ks_register_users: "{{ freezer_ks_users }}"
