---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ openvswitch_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    container_engine: "{{ kolla_container_engine }}"
    name:
      - openvswitch_db
  check_mode: false
  register: container_facts

- name: Checking free port for OVSDB
  vars:
    openvswitch_db: "{{ openvswitch_services['openvswitch-db-server'] }}"
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ ovsdb_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['openvswitch_db'] is not defined
    - inventory_hostname in groups[openvswitch_db.group]
    - openvswitch_db.enabled | bool
