---
storm_services:
  storm-worker:
    container_name: storm_worker
    group: storm-worker
    enabled: "{{ enable_storm | bool }}"
    image: "{{ storm_image_full }}"
    environment:
      STORM_LOG_DIR: /var/log/kolla/storm
      STORM_LOG4J_PROP: "{{ storm_log_settings }}"
    volumes: "{{ storm_worker_default_volumes + storm_nimbus_extra_volumes }}"
    dimensions: "{{ storm_worker_dimensions }}"
  storm-nimbus:
    container_name: storm_nimbus
    group: storm-nimbus
    enabled: "{{ enable_storm | bool }}"
    image: "{{ storm_image_full }}"
    environment:
      STORM_LOG_DIR: /var/log/kolla/storm
      STORM_LOG4J_PROP: "{{ storm_log_settings }}"
    volumes: "{{ storm_nimbus_default_volumes + storm_nimbus_extra_volumes }}"
    dimensions: "{{ storm_nimbus_dimensions }}"

####################
# Storm
####################
storm_log_settings: 'INFO,ROLLINGFILE'
storm_nimbus_servers: "{% for host in groups['storm-nimbus'] %}'{{ 'api' | kolla_address(host) }}'{% if not loop.last %},{% endif %}{% endfor %}"

####################
# Docker
####################
storm_install_type: "{{ kolla_install_type }}"
storm_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ storm_install_type }}-storm"
storm_tag: "{{ openstack_tag }}"
storm_image_full: "{{ storm_image }}:{{ storm_tag }}"

storm_worker_dimensions: "{{ default_container_dimensions }}"
storm_nimbus_dimensions: "{{ default_container_dimensions }}"

storm_worker_default_volumes:
  - "{{ node_config_directory }}/storm-worker/:{{ container_config_directory }}/"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "storm:/var/lib/storm/data"
  - "kolla_logs:/var/log/kolla/"
storm_nimbus_default_volumes:
  - "{{ node_config_directory }}/storm-nimbus/:{{ container_config_directory }}/"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "storm:/var/lib/storm/data"
  - "kolla_logs:/var/log/kolla/"

storm_extra_volumes: "{{ default_extra_volumes }}"
storm_worker_extra_volumes: "{{ storm_extra_volumes }}"
storm_nimbus_extra_volumes: "{{ storm_extra_volumes }}"
