---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ iscsi_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - iscsid
  register: container_facts

- name: Checking free port for iscsi
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ iscsi_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['iscsid'] is not defined
    - inventory_hostname in groups[iscsi_services.iscsid.group]
    - iscsi_services.iscsid.enabled | bool

- name: Check supported platforms for tgtd
  fail:
    msg:
      The SCSI target daemon tgtd is not supported on CentOS/RHEL 8 and later
  when:
    - ansible_facts.os_family == 'RedHat'
    - enable_tgtd | bool
