---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_ironic_auth }}"
    service_ks_register_services: "{{ ironic_ks_services }}"
    service_ks_register_users: "{{ ironic_ks_users }}"
