---
- import_tasks: config-host.yml

- import_tasks: config.yml

- import_tasks: check-containers.yml

- include_tasks: register.yml
  when: elasticsearch_enable_keystone_registration | bool

- name: Flush handlers
  meta: flush_handlers
