---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ elasticsearch_openstack_auth }}"
    service_ks_register_services: "{{ elasticsearch_ks_services }}"
  tags: always
