---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ qinling_services }}"

- include_tasks: external_kubernetes.yml
  when:
    - (enable_qinling | bool) and (qinling_kubernetes_certificates | bool)
    - inventory_hostname in groups['qinling-engine']

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  run_once: True
  register: qinling_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/qinling/"
      skip: true

- name: Set qinling policy file
  set_fact:
    qinling_policy_file: "{{ qinling_policy.results.0.stat.path | basename }}"
    qinling_policy_file_path: "{{ qinling_policy.results.0.stat.path }}"
  when:
    - qinling_policy.results

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ qinling_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over qinling.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/qinling.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/qinling.conf"
      - "{{ node_custom_config }}/qinling/{{ item.key }}.conf"
      - "{{ node_custom_config }}/qinling/{{ inventory_hostname }}/qinling.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/qinling.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ qinling_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over wsgi-qinling files for services
  vars:
    service: "{{ qinling_services['qinling-api'] }}"
  template:
    src: "wsgi-qinling.conf.j2"
    dest: "{{ node_config_directory }}/qinling-api/wsgi-qinling.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart qinling-api container

- name: Copying over existing policy file
  template:
    src: "{{ qinling_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ qinling_policy_file }}"
    mode: "0660"
  become: true
  when:
    - qinling_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ qinling_services }}"
  notify:
    - Restart {{ item.key }} container
