---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_qinling_auth }}"
    service_ks_register_services: "{{ qinling_ks_services }}"
    service_ks_register_users: "{{ qinling_ks_users }}"
