---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ magnum_services }}"

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  run_once: True
  register: magnum_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/magnum/"
      skip: true

- name: Set magnum policy file
  set_fact:
    magnum_policy_file: "{{ magnum_policy.results.0.stat.path | basename }}"
    magnum_policy_file_path: "{{ magnum_policy.results.0.stat.path }}"
  when:
    - magnum_policy.results

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ magnum_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over magnum.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/magnum.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/magnum.conf"
      - "{{ node_custom_config }}/magnum/{{ item.key }}.conf"
      - "{{ node_custom_config }}/magnum/{{ inventory_hostname }}/magnum.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/magnum.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ magnum_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over existing policy file
  template:
    src: "{{ magnum_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ magnum_policy_file }}"
    mode: "0660"
  become: true
  when:
    - magnum_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ magnum_services }}"
  notify:
    - Restart {{ item.key }} container
