---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ monasca_openstack_auth }}"
    service_ks_register_services: "{{ monasca_ks_services }}"
    service_ks_register_users: "{{ monasca_ks_users }}"
    service_ks_register_roles: "{{ monasca_ks_roles }}"
