---
project_name: "searchlight"

searchlight_services:
  searchlight-api:
    container_name: searchlight_api
    group: searchlight-api
    enabled: true
    image: "{{ searchlight_api_image_full }}"
    volumes: "{{ searchlight_api_default_volumes + searchlight_api_extra_volumes }}"
    dimensions: "{{ searchlight_api_dimensions }}"
    haproxy:
      searchlight_api:
        enabled: "{{ enable_searchlight }}"
        mode: "http"
        external: false
        port: "{{ searchlight_api_port }}"
      searchlight_api_external:
        enabled: "{{ enable_searchlight }}"
        mode: "http"
        external: true
        port: "{{ searchlight_api_port }}"
  searchlight-listener:
    container_name: searchlight_listener
    group: searchlight-listener
    enabled: true
    image: "{{ searchlight_listener_image_full }}"
    volumes: "{{ searchlight_listener_default_volumes + searchlight_listener_extra_volumes }}"
    dimensions: "{{ searchlight_listener_dimensions }}"

####################
# Elasticsearch
####################
searchlight_elasticsearch_url: "{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ elasticsearch_port }}"

####################
# Docker
####################
searchlight_install_type: "{{ kolla_install_type }}"
searchlight_tag: "{{ openstack_tag }}"

searchlight_listener_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ searchlight_install_type }}-searchlight-listener"
searchlight_listener_tag: "{{ searchlight_tag }}"
searchlight_listener_image_full: "{{ searchlight_listener_image }}:{{ searchlight_listener_tag }}"

searchlight_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ searchlight_install_type }}-searchlight-api"
searchlight_api_tag: "{{ searchlight_tag }}"
searchlight_api_image_full: "{{ searchlight_api_image }}:{{ searchlight_api_tag }}"

searchlight_api_dimensions: "{{ default_container_dimensions }}"
searchlight_listener_dimensions: "{{ default_container_dimensions }}"

searchlight_api_default_volumes:
  - "{{ node_config_directory }}/searchlight-api/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "kolla_logs:/var/log/kolla/"
searchlight_listener_default_volumes:
  - "{{ node_config_directory }}/searchlight-listener/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "kolla_logs:/var/log/kolla/"

searchlight_extra_volumes: "{{ default_extra_volumes }}"
searchlight_api_extra_volumes: "{{ searchlight_extra_volumes }}"
searchlight_listener_extra_volumes: "{{ searchlight_extra_volumes }}"

####################
# OpenStack
####################
searchlight_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ searchlight_api_port }}"
searchlight_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ searchlight_api_port }}"
searchlight_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn | put_address_in_context('url') }}:{{ searchlight_api_port }}"

searchlight_logging_debug: "{{ openstack_logging_debug }}"

searchlight_keystone_user: "searchlight"

openstack_searchlight_auth: "{{ openstack_auth }}"


####################
# Notifications
####################
searchlight_notification_topics:
  - name: notifications
    enabled: "{{ enable_ceilometer | bool }}"

searchlight_enabled_notification_topics: "{{ searchlight_notification_topics | selectattr('enabled', 'equalto', true) | list }}"

####################
# Keystone
####################
searchlight_ks_services:
  - name: "searchlight"
    type: "search"
    description: "Openstack Index Service"
    endpoints:
      - {'interface': 'admin', 'url': '{{ searchlight_admin_endpoint }}'}
      - {'interface': 'internal', 'url': '{{ searchlight_internal_endpoint }}'}
      - {'interface': 'public', 'url': '{{ searchlight_public_endpoint }}'}

searchlight_ks_users:
  - project: "service"
    user: "{{ searchlight_keystone_user }}"
    password: "{{ searchlight_keystone_password }}"
    role: "admin"
