---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ cinder_services }}"

- include_tasks: external_ceph.yml
  when:
    - cinder_backend_ceph | bool
    - inventory_hostname in groups['cinder-volume'] or
      inventory_hostname in groups['cinder-backup']

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  run_once: True
  register: cinder_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/cinder/"
      skip: true

- name: Set cinder policy file
  set_fact:
    cinder_policy_file: "{{ cinder_policy.results.0.stat.path | basename }}"
    cinder_policy_file_path: "{{ cinder_policy.results.0.stat.path }}"
  when:
    - cinder_policy.results

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool or cinder_enable_tls_backend | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ cinder_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over cinder-wsgi.conf
  vars:
    service: "{{ cinder_services['cinder-api'] }}"
  become: true
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/cinder-api/cinder-wsgi.conf"
    mode: "0660"
  with_first_found:
    - "{{ node_custom_config }}/cinder/{{ inventory_hostname }}/cinder-wsgi.conf"
    - "{{ node_custom_config }}/cinder/cinder-wsgi.conf"
    - "cinder-wsgi.conf.j2"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart cinder-api container

- name: Copying over cinder.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/cinder.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/cinder.conf"
      - "{{ node_custom_config }}/cinder/{{ item.key }}.conf"
      - "{{ node_custom_config }}/cinder/{{ inventory_hostname }}/cinder.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/cinder.conf"
    mode: "0660"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ cinder_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over existing policy file
  become: true
  template:
    src: "{{ cinder_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ cinder_policy_file }}"
    mode: "0660"
  when:
    - item.value.enabled | bool
    - cinder_policy_file is defined
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ cinder_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over nfs_shares files for cinder_volume
  become: true
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/cinder-volume/nfs_shares"
    mode: "0660"
  with_first_found:
    - files:
        - "{{ node_custom_config }}/nfs_shares.j2"
        - "{{ node_custom_config }}/cinder/nfs_shares.j2"
        - "{{ node_custom_config }}/cinder/cinder-volume/nfs_shares.j2"
        - "{{ node_custom_config }}/cinder/{{ inventory_hostname }}/nfs_shares.j2"
        - "{{ node_custom_config }}/nfs_shares"
        - "{{ node_custom_config }}/cinder/nfs_shares"
        - "{{ node_custom_config }}/cinder/cinder-volume/nfs_shares"
        - "{{ node_custom_config }}/cinder/{{ inventory_hostname }}/nfs_shares"
      skip: "{{ not enable_cinder_backend_nfs | bool and not enable_cinder_backend_hnas_nfs | bool }}"
  when: inventory_hostname in groups['cinder-volume']
  notify:
    - Restart cinder-volume container
