---
- import_tasks: config.yml

- import_tasks: check-containers.yml

- import_tasks: bootstrap.yml
  when: inventory_hostname in groups['ovn-controller']

- name: Flush handlers
  meta: flush_handlers
