---
- name: Check octavia containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    dimensions: "{{ item.value.dimensions }}"
  when:
    - inventory_hostname in groups.get(item.value.group, [])
    - item.value.enabled | bool
  with_dict: "{{ octavia_services }}"
  notify:
    - "Restart {{ item.key }} container"
