---
- include_tasks: hm-interface.yml
  when:
    - octavia_auto_configure | bool
    - octavia_network_type == "tenant"
    - inventory_hostname in groups[octavia_services['octavia-health-manager']['group']]
