---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/influxdb"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ influxdb_services }}"

- name: Copying over config.json files
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/influxdb/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ influxdb_services }}"
  notify:
    - Restart influxdb container

- name: Copying over influxdb config file
  vars:
    service: "{{ influxdb_services['influxdb'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/influxdb/influxdb.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/influxdb/{{ inventory_hostname }}/influxdb.conf"
    - "{{ node_custom_config }}/influxdb.conf"
    - "influxdb.conf.j2"
  notify:
    - Restart influxdb container
