---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ manila_services }}"

- include_tasks: ceph.yml
  when:
    - enable_ceph | bool
    - enable_ceph_mds | bool
    - (enable_manila_backend_cephfs_native | bool) or (enable_manila_backend_cephfs_nfs | bool)
    - inventory_hostname in groups['manila-share']

- include_tasks: external_ceph.yml
  when:
    - enable_ceph| bool == False
    - enable_ceph_mds| bool == False
    - (enable_manila_backend_cephfs_native | bool) or (enable_manila_backend_cephfs_nfs | bool)
    - inventory_hostname in groups['manila-share']

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: manila_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/manila/"
      skip: true

- name: Set manila policy file
  set_fact:
    manila_policy_file: "{{ manila_policy.results.0.stat.path | basename }}"
    manila_policy_file_path: "{{ manila_policy.results.0.stat.path }}"
  when:
    - manila_policy.results

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ manila_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over manila.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/manila.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/manila.conf"
      - "{{ node_custom_config }}/manila/{{ item.key }}.conf"
      - "{{ node_custom_config }}/manila/{{ inventory_hostname }}/manila.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/manila.conf"
    mode: "0660"
  become: true
  when:
    - item.key in [ "manila-api", "manila-data", "manila-scheduler" ]
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ manila_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over manila-share.conf
  vars:
    service: "{{ manila_services['manila-share'] }}"
    service_name: "{{ item }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/manila.conf.j2"
      - "{{ role_path }}/templates/manila-share.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/manila.conf"
      - "{{ node_custom_config }}/{{ item }}.conf"
      - "{{ node_custom_config }}/manila/{{ item }}.conf"
      - "{{ node_custom_config }}/manila/{{ inventory_hostname }}/manila.conf"
    dest: "{{ node_config_directory }}/{{ item }}/manila.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_items:
    - "manila-share"
  notify:
    - Restart manila-share container

- name: Copying over existing policy file
  template:
    src: "{{ manila_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ manila_policy_file }}"
    mode: "0660"
  when:
    - manila_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ manila_services }}"
  notify:
    - "Restart {{ item.key }} container"
