---
- include_tasks: clone.yml
  when: manila_dev_mode | bool

- import_tasks: register.yml

- import_tasks: config.yml

- import_tasks: check-containers.yml

- import_tasks: bootstrap.yml

- name: Flush handlers
  meta: flush_handlers
