---
- include_tasks: clone.yml
  when: manila_dev_mode | bool

- import_tasks: register.yml

- import_tasks: config.yml

- import_tasks: bootstrap.yml

- name: Flush handlers
  meta: flush_handlers

- include_tasks: fix_cephfs_owner.yml
  when:
    - enable_manila_backend_cephfs_native | bool
    - inventory_hostname in groups['manila-share']
