---
- name: Create bridge
  become: true
  command: ip link add {{ bridge_name }} type bridge

- name: Bring bridge interface up
  become: true
  command: ip link set {{ bridge_name }} up

- name: Add member interface to bridge
  become: true
  command: ip link set {{ bridge_member_name }} master {{ bridge_name }}
