---
- name: "{{ kolla_role_name | default(project_name) }} | Pull images"
  vars:
    service: "{{ item.value }}"
  become: true
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ service.image }}"
  with_dict: "{{ lookup('vars', (kolla_role_name | default(project_name)) + '_services') | select_services_enabled_and_mapped_to_host }}"
  loop_control:
    label: "{{ item.key }}"
