---
- import_role:
    name: service-config-validate
  vars:
    service_config_validate_services: "{{ solum_services }}"
    service_name: "{{ project_name }}"
    service_config_validation: "{{ solum_config_validation }}"
