---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ solum_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    container_engine: "{{ kolla_container_engine }}"
    name:
      - solum_api
  check_mode: false
  register: container_facts

- name: Checking free port for Solum Application Deployment
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ solum_application_deployment_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['solum_api'] is not defined
    - inventory_hostname in groups['solum-api']

- name: Checking free port for Solum Image Builder
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ solum_image_builder_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['solum_api'] is not defined
    - inventory_hostname in groups['solum-api']
