---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_solum_auth }}"
    service_ks_register_services: "{{ solum_ks_services }}"
    service_ks_register_users: "{{ solum_ks_users }}"
