---
####################
# Docker
####################
bifrost_install_type: "{{ kolla_install_type }}"
bifrost_tag: "{{ openstack_tag }}"

bifrost_deploy_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ bifrost_install_type }}-bifrost-deploy"
bifrost_deploy_tag: "{{ bifrost_tag }}"
bifrost_deploy_image_full: "{{ bifrost_deploy_image }}:{{ bifrost_deploy_tag }}"

bifrost_deploy_container_proxy: "{{ container_proxy }}"
