---
- name: Ensuring collectd config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ collectd_services }}"

- name: Ensuring Plugin directory exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}/collectd.conf.d"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ collectd_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ collectd_services }}"
  notify:
    - Restart collectd container

- name: Copying over collectd.conf for services
  vars:
    service: "{{ collectd_services['collectd'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/collectd/collectd.conf"
    mode: "0660"
  become: true
  with_first_found:
    - "{{ node_custom_config }}/collectd/{{ inventory_hostname }}/collectd.conf"
    - "{{ node_custom_config }}/collectd/collectd.conf"
    - "{{ node_custom_config }}/collectd.conf"
    - "collectd.conf.j2"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart collectd container
