---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ qdrouterd_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ qdrouterd_services }}"
  notify:
    - Restart qdrouterd container

- name: Copying over qdrouterd config
  vars:
    service: "{{ qdrouterd_services['qdrouterd'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/qdrouterd/qdrouterd.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/qdrouterd/{{ inventory_hostname }}/qdrouterd.conf"
    - "{{ node_custom_config }}/qdrouterd/qdrouterd.conf"
    - "qdrouterd.conf.j2"
  notify:
    - Restart qdrouterd container

- name: Copying over qdrouterd sasl config
  vars:
    service: "{{ qdrouterd_services['qdrouterd'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/qdrouterd/qdrouterd-sasl.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/qdrouterd/{{ inventory_hostname }}/qdrouterd-sasl.conf"
    - "{{ node_custom_config }}/qdrouterd/qdrouterd-sasl.conf"
    - "qdrouterd-sasl.conf.j2"
  notify:
    - Restart qdrouterd container
