---
- import_playbook: gather-facts.yml
  when: >-
    kolla_enable_tls_backend | default(false) | bool or
    rabbitmq_enable_tls | default(false) | bool

- name: Apply role certificates
  hosts: localhost
  roles:
    - certificates
