---
- name: Creating admin openrc file on the deploy node
  hosts: localhost
  tasks:
    - name: Template out admin-openrc.sh
      become: true
      template:
        src: "roles/common/templates/admin-openrc.sh.j2"
        dest: "{{ node_config }}/admin-openrc.sh"
        owner: "{{ ansible_facts.user_uid }}"
        group: "{{ ansible_facts.user_gid }}"
        mode: 0600

    - import_role:
        name: octavia
        tasks_from: openrc.yml
      when: enable_octavia | bool
