---
tempest_services:
  tempest:
    container_name: "tempest"
    image: "{{ tempest_image_full }}"
    enabled: true
    group: "tempest"
    volumes: "{{ tempest_default_volumes + tempest_extra_volumes }}"
    dimensions: "{{ tempest_dimensions }}"


########
# Docker
########
tempest_install_type: "{{ kolla_install_type }}"
tempest_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ tempest_install_type }}-tempest"
tempest_tag: "{{ openstack_tag }}"
tempest_image_full: "{{ tempest_image }}:{{ tempest_tag }}"
tempest_dimensions: "{{ default_container_dimensions }}"

tempest_default_volumes:
  - "{{ node_config_directory }}/tempest/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "kolla_logs:/var/log/kolla/"

tempest_extra_volumes: "{{ default_extra_volumes }}"

###########################
# Tempest Required Resource
###########################
tempest_image_url: "{{ image_url | default('https://github.com/cirros-dev/cirros/releases/download/0.5.1/cirros-0.5.1-x86_64-disk.img') }}"

tempest_image_id:
tempest_image_alt_id: "{{ tempest_image_id }}"
tempest_flavor_ref_id:
tempest_flavor_ref_alt_id: "{{ tempest_flavor_ref_id }}"
tempest_public_network_id:
tempest_floating_network_name:
tempest_image_ssh_user: cirros
tempest_image_ssh_password: gocubsgo
