---
- name: Ensure apt sources list directory exists
  file:
    path: /etc/apt/sources.list.d
    state: directory
    recurse: yes
  become: True

- name: Enable Ceph apt repository
  apt_repository:
    repo: "{{ cephadm_ceph_apt_repo }}"
    filename: ceph
  become: True
