---
- job:
    name: kolla-ansible-base
    pre-run: tests/pre.yml
    run: tests/run.yml
    post-run: tests/post.yml
    attempts: 5
    timeout: 7200
    required-projects:
      - openstack/kolla
      - openstack/kolla-ansible
      - openstack/requirements
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*
      - ^lower-constraints.txt$
      - ^releasenotes/.*$
      - ^test-requirements.txt$
    vars:
      scenario: aio
      enable_core_openstack: yes
    host-vars:
      primary:
        ansible_python_interpreter: python2
      secondary1:
        ansible_python_interpreter: python2
      secondary2:
        ansible_python_interpreter: python2
    roles:
      - zuul: zuul/zuul-jobs

- job:
    name: kolla-ansible-upgrade-base
    parent: kolla-ansible-base
    voting: false
    vars:
      previous_release: rocky
      scenario: upgrade

- job:
    name: kolla-ansible-bifrost-base
    parent: kolla-ansible-base
    vars:
      scenario: bifrost
      install_type: source
      enable_core_openstack: no

- job:
    name: kolla-ansible-ironic-base
    parent: kolla-ansible-base
    voting: false
    files:
      - ^ansible/roles/(ironic|nova)/
      - ^tests/test-ironic.sh
    vars:
      scenario: ironic
