---
- project:
    queue: kolla
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - ansible-role-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
    check:
      jobs:
        - kolla-ansible-centos9s
        - kolla-ansible-debian
        - kolla-ansible-openeuler
        - kolla-ansible-rocky9
        - kolla-ansible-ubuntu
        - kolla-ansible-rocky9-kvm
        - kolla-ansible-ubuntu-kvm
        - kolla-ansible-rocky9-multinode-ipv6
        - kolla-ansible-ubuntu-multinode-ipv6
        - kolla-ansible-rocky9-bifrost
        - kolla-ansible-ubuntu-bifrost
        - kolla-ansible-rocky9-zun
        - kolla-ansible-debian-zun
        - kolla-ansible-ubuntu-zun
        - kolla-ansible-rocky9-swift
        - kolla-ansible-ubuntu-swift
        - kolla-ansible-rocky9-scenario-nfv
        - kolla-ansible-rocky9-magnum
        - kolla-ansible-ubuntu-magnum
        - kolla-ansible-rocky9-octavia
        - kolla-ansible-ubuntu-octavia
        - kolla-ansible-rocky9-masakari
        - kolla-ansible-ubuntu-masakari
        - kolla-ansible-rocky9-ironic
        - kolla-ansible-debian-ironic
        - kolla-ansible-ubuntu-ironic
        - kolla-ansible-rocky9-upgrade
        - kolla-ansible-debian-upgrade
        - kolla-ansible-ubuntu-upgrade
        - kolla-ansible-ubuntu-cells
        - kolla-ansible-rocky9-cells
        - kolla-ansible-rocky9-mariadb
        - kolla-ansible-ubuntu-mariadb
        - kolla-ansible-rocky9-ovn
        - kolla-ansible-ubuntu-ovn
        - kolla-ansible-rocky9-upgrade-ovn
        - kolla-ansible-ubuntu-upgrade-ovn
        - kolla-ansible-rocky9-prometheus-opensearch
        - kolla-ansible-ubuntu-prometheus-opensearch
        - kolla-ansible-rocky9-prometheus-opensearch-upgrade
        - kolla-ansible-ubuntu-prometheus-opensearch-upgrade
        - kolla-ansible-rocky9-venus
        - kolla-ansible-ubuntu-venus
        - kolla-ansible-rocky9-cephadm
        - kolla-ansible-ubuntu-cephadm
        - kolla-ansible-rocky9-upgrade-cephadm
        - kolla-ansible-ubuntu-upgrade-cephadm
        - kolla-ansible-rocky9-hashi-vault
    check-arm64:
      jobs:
        - kolla-ansible-debian-aarch64
        - kolla-ansible-debian-upgrade-aarch64
    gate:
      jobs:
        - kolla-ansible-debian
        - kolla-ansible-debian-upgrade
        - kolla-ansible-rocky9
        - kolla-ansible-rocky9-upgrade
        - kolla-ansible-ubuntu
        - kolla-ansible-ubuntu-upgrade
    experimental:
      jobs:
        - kolla-ansible-rocky9-swift-upgrade
        - kolla-ansible-ubuntu-swift-upgrade
