---
- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - ansible-role-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
    check:
      jobs:
        - kolla-ansible-centos8-source
        - kolla-ansible-debian-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-ubuntu-source-multinode-ipv6
        - kolla-ansible-centos8-source-bifrost
        - kolla-ansible-centos8-source-zun
        - kolla-ansible-ubuntu-source-zun
        - kolla-ansible-centos8-source-swift
        - kolla-ansible-ubuntu-source-swift
        - kolla-ansible-centos8-source-scenario-nfv
        - kolla-ansible-centos8-source-masakari
        - kolla-ansible-ubuntu-source-masakari
        - kolla-ansible-centos8-source-ironic
        - kolla-ansible-centos8-binary-ironic
        - kolla-ansible-ubuntu-source-ironic
        - kolla-ansible-centos8-source-upgrade
        - kolla-ansible-debian-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
        - kolla-ansible-centos8-binary
        - kolla-ansible-ubuntu-binary
        - kolla-ansible-centos8-source-cells
        - kolla-ansible-centos8-source-mariadb
        - kolla-ansible-ubuntu-source-mariadb
        - kolla-ansible-centos8-source-ceph-ansible
        - kolla-ansible-ubuntu-source-ceph-ansible
        - kolla-ansible-centos8-source-upgrade-ceph-ansible
        - kolla-ansible-ubuntu-source-upgrade-ceph-ansible
        - kolla-ansible-ubuntu-source-linuxbridge
        - kolla-ansible-centos8-source-ovn
        - kolla-ansible-ubuntu-source-ovn
        - kolla-ansible-centos8-source-prometheus-efk
        - kolla-ansible-ubuntu-source-prometheus-efk
    check-arm64:
      jobs:
        - kolla-ansible-debian-source-aarch64
        - kolla-ansible-debian-source-upgrade-aarch64
    gate:
      queue: kolla
      jobs:
        - kolla-ansible-centos8-source
        - kolla-ansible-centos8-source-upgrade
        - kolla-ansible-ubuntu-source
        - kolla-ansible-ubuntu-source-upgrade
