---
- project:
    queue: kolla
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-yoga-jobs
      - ansible-role-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
    check:
      jobs:
        - kolla-ansible-centos8s-source
        - kolla-ansible-centos9s-source
        - kolla-ansible-debian-source
        - kolla-ansible-rocky8-source
        - kolla-ansible-rocky9-source
        - kolla-ansible-ubuntu-source-focal
        - kolla-ansible-ubuntu-source-jammy
        - kolla-ansible-centos8s-source-kvm
        - kolla-ansible-rocky9-source-kvm
        - kolla-ansible-ubuntu-source-kvm-focal
        - kolla-ansible-centos8s-source-multinode-ipv6
        - kolla-ansible-rocky9-source-multinode-ipv6
        - kolla-ansible-ubuntu-source-multinode-ipv6-focal
        - kolla-ansible-centos8s-source-bifrost
        - kolla-ansible-rocky9-source-bifrost
        - kolla-ansible-ubuntu-source-bifrost-focal
        - kolla-ansible-centos8s-source-zun
        - kolla-ansible-rocky9-source-zun
        - kolla-ansible-debian-source-zun
        - kolla-ansible-ubuntu-source-zun-focal
        - kolla-ansible-centos8s-source-swift
        - kolla-ansible-rocky9-source-swift
        - kolla-ansible-ubuntu-source-swift-focal
        - kolla-ansible-centos8s-source-scenario-nfv
        - kolla-ansible-rocky9-source-scenario-nfv
        - kolla-ansible-centos8s-source-magnum
        - kolla-ansible-rocky9-source-magnum
        - kolla-ansible-ubuntu-source-magnum-focal
        - kolla-ansible-centos8s-source-octavia
        - kolla-ansible-rocky9-source-octavia
        - kolla-ansible-ubuntu-source-octavia-focal
        - kolla-ansible-centos8s-source-masakari
        - kolla-ansible-rocky9-source-masakari
        - kolla-ansible-ubuntu-source-masakari-focal
        - kolla-ansible-centos8s-source-ironic
        - kolla-ansible-rocky9-source-ironic
        - kolla-ansible-centos8s-binary-ironic
        - kolla-ansible-debian-source-ironic
        - kolla-ansible-ubuntu-source-ironic-focal
        - kolla-ansible-centos8s-source-upgrade
        - kolla-ansible-debian-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade-focal
        - kolla-ansible-centos8s-binary
        - kolla-ansible-ubuntu-binary-focal
        - kolla-ansible-centos8s-source-cells
        - kolla-ansible-rocky9-source-cells
        - kolla-ansible-centos8s-source-mariadb
        - kolla-ansible-rocky9-source-mariadb
        - kolla-ansible-ubuntu-source-mariadb-focal
        - kolla-ansible-centos8s-source-linuxbridge
        - kolla-ansible-rocky9-source-linuxbridge
        - kolla-ansible-ubuntu-source-linuxbridge-focal
        - kolla-ansible-centos8s-source-ovn
        - kolla-ansible-rocky9-source-ovn
        - kolla-ansible-ubuntu-source-ovn-focal
        - kolla-ansible-centos8s-source-prometheus-efk
        - kolla-ansible-ubuntu-source-prometheus-efk-focal
        - kolla-ansible-centos8s-source-prometheus-opensearch
        - kolla-ansible-centos8s-source-prometheus-opensearch-migration
        - kolla-ansible-ubuntu-source-prometheus-opensearch
        - kolla-ansible-ubuntu-source-prometheus-opensearch-migration-focal
        - kolla-ansible-rocky9-source-prometheus-opensearch
        - kolla-ansible-centos8s-source-cephadm
        - kolla-ansible-rocky9-source-cephadm
        - kolla-ansible-ubuntu-source-cephadm-focal
        - kolla-ansible-centos8s-source-upgrade-cephadm
        - kolla-ansible-ubuntu-source-upgrade-cephadm-focal
        - kolla-ansible-centos8s-hashi-vault
        - kolla-ansible-rocky9-hashi-vault
    check-arm64:
      jobs:
        - kolla-ansible-debian-source-aarch64
        - kolla-ansible-debian-source-upgrade-aarch64
    gate:
      jobs:
        - kolla-ansible-centos8s-source
        - kolla-ansible-centos8s-source-upgrade
        - kolla-ansible-debian-source
        - kolla-ansible-debian-source-upgrade
        - kolla-ansible-rocky9-source
        - kolla-ansible-ubuntu-source-focal
        - kolla-ansible-ubuntu-source-jammy
        - kolla-ansible-ubuntu-source-upgrade-focal
    experimental:
      jobs:
        - kolla-ansible-centos8s-source-swift-upgrade
        - kolla-ansible-ubuntu-source-swift-upgrade-focal
