---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ cyborg_services }}"

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  run_once: True
  register: cyborg_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/cyborg/"
      skip: true

- name: Set cyborg policy file
  set_fact:
    cyborg_policy_file: "{{ cyborg_policy.results.0.stat.path | basename }}"
    cyborg_policy_file_path: "{{ cyborg_policy.results.0.stat.path }}"
  when:
    - cyborg_policy.results

- name: Copying over existing policy file
  template:
    src: "{{ cyborg_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ cyborg_policy_file }}"
    mode: "0660"
  become: true
  when:
    - cyborg_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ cyborg_services }}"
  notify:
    - Restart {{ item.key }} container

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ cyborg_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over cyborg.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/cyborg.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/cyborg.conf"
      - "{{ node_custom_config }}/cyborg/{{ item.key }}.conf"
      - "{{ node_custom_config }}/cyborg/{{ inventory_hostname }}/cyborg.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/cyborg.conf"
    mode: "0660"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ cyborg_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over cyborg-api-paste.ini
  vars:
    service: "{{ cyborg_services['cyborg-api'] }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/cyborg-api-paste.ini.j2"
      - "{{ node_custom_config }}/cyborg/cyborg-api-paste.ini"
    dest: "{{ node_config_directory }}/cyborg-api/api-paste.ini"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups['cyborg-api']
    - service.enabled | bool
  notify:
    - Restart cyborg-api container
