---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ kibana_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    container_engine: "{{ kolla_container_engine }}"
    name:
      - kibana
  register: container_facts

- name: Checking free port for Kibana Server
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ kibana_server_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['kibana'] is not defined
    - inventory_hostname in groups['kibana']
