---
- name: Check skyline container
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes | reject('equalto', '') | list }}"
    dimensions: "{{ item.value.dimensions }}"
    healthcheck: "{{ horizon.healthcheck | default(omit) }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ skyline_services }}"
  notify:
    - "Restart {{ item.key }} container"
