---
- name: "Stopping skyline containers"
  vars:
    service: "{{ item.value }}"
  docker_container:
    name: "{{ service.container_name }}"
    state: stopped
  when:
    - service.enabled | bool
    - service.container_name not in skip_stop_containers
  with_dict: "{{ skyline_services }}"
