---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_heat_auth }}"
    service_ks_register_services: "{{ heat_ks_services }}"
    service_ks_register_users: "{{ heat_ks_users }}"
    service_ks_register_roles: "{{ heat_ks_roles }}"
    service_ks_register_user_roles: "{{ heat_ks_user_roles }}"
