---
- name: Setup OpenStack clients
  ansible.builtin.pip:
    name: "{{ item.package }}"
    virtualenv: "{{ openstack_clients_venv_path }}"
    virtualenv_command: "python3 -m venv"
  become: true
  when: item.enabled
  loop: "{{ openstack_clients_pip_packages }}"
