---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ vmtp_services }}"

- name: Copying over configuration file for vmtp
  vars:
    service: "{{ vmtp_services['vmtp'] }}"
  merge_yaml:
    sources:
      - "{{ role_path }}/templates/{{ item }}.j2"
      - "{{ node_custom_config }}/{{ item }}"
      - "{{ node_custom_config }}/vmtp/{{ item }}"
    dest: "{{ node_config_directory }}/vmtp/{{ item }}"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_items:
    - "cfg.default.yaml"
  notify:
    - Restart vmtp container
