---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ senlin_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    container_engine: "{{ kolla_container_engine }}"
    name:
      - senlin_api
  check_mode: false
  register: container_facts

- name: Checking free port for Senlin API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ senlin_api_listen_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['senlin_api'] is not defined
    - inventory_hostname in groups['senlin-api']
