---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_senlin_auth }}"
    service_ks_register_services: "{{ senlin_ks_services }}"
    service_ks_register_users: "{{ senlin_ks_users }}"
