---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sahara_services }}"

- name: Check if policies shall be overwritten
  stat:
    path: "{{ item }}"
  delegate_to: localhost
  run_once: True
  register: sahara_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/sahara/"
      skip: true

- name: Set sahara policy file
  set_fact:
    sahara_policy_file: "{{ sahara_policy.results.0.stat.path | basename }}"
    sahara_policy_file_path: "{{ sahara_policy.results.0.stat.path }}"
  when:
    - sahara_policy.results

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sahara_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over sahara.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/sahara.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/sahara.conf"
      - "{{ node_custom_config }}/sahara/{{ item.key }}.conf"
      - "{{ node_custom_config }}/sahara/{{ inventory_hostname }}/sahara.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/sahara.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sahara_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over existing policy file
  template:
    src: "{{ sahara_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ sahara_policy_file }}"
    mode: "0660"
  become: true
  when:
    - sahara_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ sahara_services }}"
  notify:
    - Restart {{ item.key }} container
