---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ sahara_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    container_engine: "{{ kolla_container_engine }}"
    name:
      - sahara_api
  check_mode: false
  register: container_facts

- name: Checking free port for Sahara API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ sahara_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['sahara_api'] is not defined
    - inventory_hostname in groups['sahara-api']
