---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_sahara_auth }}"
    service_ks_register_services: "{{ sahara_ks_services }}"
    service_ks_register_users: "{{ sahara_ks_users }}"
