---
- import_tasks: register.yml

- import_tasks: config.yml

- include_tasks: clone.yml
  when: designate_dev_mode | bool

- import_tasks: bootstrap.yml

- name: Flush handlers
  meta: flush_handlers

- import_tasks: update_pools.yml
