---
- name: Update DNS pools
  become: true
  command: docker exec -t designate_worker designate-manage pool update --file /etc/designate/pools.yaml
  run_once: True
  delegate_to: "{{ groups['designate-worker'][0] }}"
