---
project_name: "cyborg"

cyborg_services:
  cyborg-api:
    container_name: cyborg_api
    group: cyborg-api
    enabled: true
    image: "{{ cyborg_api_image_full }}"
    volumes: "{{ cyborg_api_default_volumes + cyborg_api_extra_volumes }}"
    dimensions: "{{ cyborg_api_dimensions }}"
  cyborg-agent:
    container_name: cyborg_agent
    group: cyborg-agent
    enabled: true
    privileged: true
    image: "{{ cyborg_agent_image_full }}"
    volumes: "{{ cyborg_agent_default_volumes + cyborg_agent_extra_volumes }}"
    dimensions: "{{ cyborg_agent_dimensions }}"
  cyborg-conductor:
    container_name: cyborg_conductor
    group: cyborg-conductor
    enabled: true
    image: "{{ cyborg_conductor_image_full }}"
    volumes: "{{ cyborg_conductor_default_volumes + cyborg_conductor_extra_volumes }}"
    dimensions: "{{ cyborg_conductor_dimensions }}"

####################
# Database
####################
cyborg_database_name: "cyborg"
cyborg_database_user: "{% if use_preconfigured_databases | bool and use_common_mariadb_user | bool %}{{ database_user }}{% else %}cyborg{% endif %}"
cyborg_database_address: "{{ database_address | put_address_in_context('url') }}:{{ database_port }}"

####################
# Docker
####################
cyborg_install_type: "{{ kolla_install_type }}"
cyborg_tag: "{{ openstack_tag }}"

cyborg_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ cyborg_install_type }}-cyborg-api"
cyborg_api_tag: "{{ cyborg_tag }}"
cyborg_api_image_full: "{{ cyborg_api_image }}:{{ cyborg_api_tag }}"

cyborg_agent_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ cyborg_install_type }}-cyborg-agent"
cyborg_agent_tag: "{{ cyborg_tag }}"
cyborg_agent_image_full: "{{ cyborg_agent_image }}:{{ cyborg_agent_tag }}"

cyborg_conductor_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ cyborg_install_type }}-cyborg-conductor"
cyborg_conductor_tag: "{{ cyborg_tag }}"
cyborg_conductor_image_full: "{{ cyborg_conductor_image }}:{{ cyborg_conductor_tag }}"

cyborg_api_dimensions: "{{ default_container_dimensions }}"
cyborg_agent_dimensions: "{{ default_container_dimensions }}"
cyborg_conductor_dimensions: "{{ default_container_dimensions }}"

cyborg_api_default_volumes:
  - "{{ node_config_directory }}/cyborg-api/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "cyborg:/var/lib/cyborg/"
  - "kolla_logs:/var/log/kolla/"

cyborg_agent_default_volumes:
  - "{{ node_config_directory }}/cyborg-agent/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "kolla_logs:/var/log/kolla/"

cyborg_conductor_default_volumes:
  - "{{ node_config_directory }}/cyborg-conductor/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_facts.os_family == 'Debian' else '' }}"
  - "kolla_logs:/var/log/kolla/"

cyborg_extra_volumes: "{{ default_extra_volumes }}"
cyborg_api_extra_volumes: "{{ cyborg_extra_volumes }}"
cyborg_agent_extra_volumes: "{{ cyborg_extra_volumes }}"
cyborg_conductor_extra_volumes: "{{ cyborg_extra_volumes }}"

####################
# OpenStack
####################
cyborg_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ cyborg_api_port }}"
cyborg_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn | put_address_in_context('url') }}:{{ cyborg_api_port }}"
cyborg_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn | put_address_in_context('url') }}:{{ cyborg_api_port }}"

cyborg_logging_debug: "{{ openstack_logging_debug }}"

cyborg_keystone_user: "cyborg"

openstack_cyborg_auth: "{{ openstack_auth }}"


####################
# Notifications
####################
cyborg_notification_topics:
  - name: notifications
    enabled: "{{ enable_ceilometer | bool }}"

cyborg_enabled_notification_topics: "{{ cyborg_notification_topics | selectattr('enabled', 'equalto', true) | list }}"

####################
# Keystone
####################
cyborg_ks_services:
  - name: "cyborg"
    type: "cyborg"
    description: "OpenStack Cyborg Service"
    endpoints:
      - {'interface': 'admin', 'url': '{{ cyborg_admin_endpoint }}'}
      - {'interface': 'internal', 'url': '{{ cyborg_internal_endpoint }}'}
      - {'interface': 'public', 'url': '{{ cyborg_public_endpoint }}'}

cyborg_ks_users:
  - project: "service"
    user: "{{ cyborg_keystone_user }}"
    password: "{{ cyborg_keystone_password }}"
    role: "admin"
